version: "3"
services:
  front:
    image: node:8-alpine
    working_dir: "/var/www/app"
    environment:
      - HOST=0.0.0.0
    ports:
      - "80:3333"
    volumes:
      - ./:/var/www/app
    command: /bin/sh -c "npm install && npm run start"